### PR TITLE
Fix python3 imports and url checking logic

### PR DESCRIPTION
**Pull request by etsauer**
#### What does this PR do?
Refactor url checking so that it doesn't rely on the internet

#### How should this be tested?
Run molecule

#### Is there a relevant Issue open for this?
#91 

#### Who would you like to review this?
cc: @redhat-cop/openshift-applier

### CODE REVIEW

**Comment by oybed** [comment]
@tylerauerbeck are you sure you're running the correct branch (or tag)? The error you are seeing doesn't exist in the latest version of the repo + I know we had this issue 4-5 months ago, but has since been corrected. Hence, I suspect that maybe it's not using the correct version of this repo.

**Comment by tylerauerbeck** [comment]
@oybed Ahh -- yepp, this was me screwing up the requirements file. I fixed this and made it a bit farther -- but now I'm seeing this : 

```
NameError: global name 'urlopen' is not defined

fatal: [secrets-and-keys]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

For reference on the ansible version: 
```
ansible 2.7.0
  config file = /Users/tylerauerbeck/workspace/ci-cd/ansible.cfg
  configured module search path = [u'/Users/tylerauerbeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:47:18) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

**Comment by tylerauerbeck** [comment]
@etsauer @oybed @pcarney8 After testing this out a bit further -- these were some self-inflicted issues. This runs without issue after fixing some of my mistakes on Fedora. I'm still seeing the `urlopen` error above on my mac, but I think we can chalk that up to mac/local machine errors instead of an error with the applier.

**Comment by oybed** [comment]
@tylerauerbeck you are correct that this doesn't work for python2 (including with our `openshift-applier` container). @etsauer Can you please look to fix the support for python2?

**Pull request merged**
