### PR TITLE
change all filter_tags variables to include_tags

### PR DESCRIPTION
**Pull request by pcarney8**
#### What does this PR do?
change all the `filter_tags` to `include_tags`

#### How should this be tested?
ansible-playbook ... -e include_tags=<some-tag>

#### Is there a relevant Issue open for this?
no, sort of goes along with #124 

#### Who would you like to review this?
cc: @redhat-cop/openshift-applier

### CODE REVIEW

**Comment by jacobsee** [comment]
I also prefer maintaining backwards compatibility with `filter_tags`, at least for a while, maybe with a deprecation warning?

**Comment by pcarney8** [comment]
@oybed @jacobsee updated. Thoughts?

**Comment by pcarney8** [comment]
Gotcha. Will do. Might not be able to get to that until Friday

**Comment by oybed** [comment]
Fixed CI run by taking care of this Lint error part of this PR:
```
--> Executing Yamllint on files found in /home/travis/build/redhat-cop/openshift-applier/...
    /home/travis/build/redhat-cop/openshift-applier/roles/openshift-applier/tasks/check-for-old-vars.yml
      1:1       warning  missing document start "---"  (document-start)
```

**Pull request merged**
