### PR TITLE
Updating image to run as non-root, and package the repo

### PR DESCRIPTION
**Pull request by etsauer**
#### What does this PR do?
Packages the openshift-applier repo inside the image so we can reduce dependency management for end-users.

#### How should this be tested?
Build the image per instructions in README

Run Tests:
```
docker run -v $HOME/.kube/config:/openshift-applier/.kube/config:z -ti redhatcop/openshift-applier
```

#### Is there a relevant Issue open for this?
n/a

#### Who would you like to review this?
cc: @redhat-cop/openshift-applier

### CODE REVIEW

**Comment by sabre1041** [comment]
@etsauer Ran into an error building the image

From the base of the repository

```
$ docker build -t redhatcop/openshift-applier images/openshift-applier
...
Step 11 : COPY images/openshift-applier/root /
lstat images/openshift-applier/root: no such file or directory
```

**Comment by etsauer** [comment]
@sabre1041 just pushed an update which includes a new build command in the README.

**Comment by sabre1041** [comment]
@etsauer This is really good! Executed the default container (test) and a custom inventory.

Can you update the README with the new environment variables that can be used to drive the execution?

**Comment by etsauer** [comment]
@sabre1041 bump.

**Comment by sabre1041** [comment]
LGTM

**Pull request merged**
