### PR TITLE
🦄 allow applier to process helm charts, iterating over mappings not done yet 🦄 

### PR DESCRIPTION
**Pull request by pcarney8**
#### What does this PR do?
allows the applier to do `helm template ... | oc apply ...`

#### How should this be tested?
Run the tests playbook
`ansible-playbook playbooks/openshift-cluster-seed.yml -i tests/inventories/helm-charts`

#### Is there a relevant Issue open for this?
Don't believe so

#### Who would you like to review this?
cc: @redhat-cop/openshift-applier

### CODE REVIEW

**Comment by etsauer** [comment]
@pcarney8 can you rebase? we fixed the CI in another PR

**Comment by pcarney8** [comment]
- [ ] update README
- [ ] update helm pre-checks

Later on:
- use helmv3 ansible module when merged: 
https://github.com/ansible-collections/kubernetes/pull/61
https://github.com/ansible/ansible/issues/61546

**Comment by pcarney8** [comment]
@etsauer rebased,  @oybed updated to include pre-check and README fixed as well

**Comment by etsauer** [comment]
@pcarney8 not sure why the travis builds aren't showing up in the PR, but the linting is throwing errors: https://travis-ci.org/github/redhat-cop/openshift-applier/jobs/680227448

**Comment by tylerauerbeck** [comment]
@pcarney8 Any idea if you'll have some time to clean these last few things up?

**Comment by pcarney8** [comment]
i don't know what is up with this one:
```
$ yamllint -c molecule/yamllint.yml .
./tests/files/helm-charts/test-chart/templates/project.yaml
  3:41      error    syntax error: expected <block end>, but found '<scalar>' (syntax)
```
but the rest are fixed now

**Review by oybed — APPROVED** [review]
LGTM

**Pull request merged**
